# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4042ae259905e09b24dd6e2a41af9883c54ed7f3b68cc1df7d97abd6d5606976ed51146264ced1f1ef25ebda079abea6d80c7becd4f4e6b1534ceded4767ef35

test:
  secret_key_base: 128d3a9eedb70e9b19e879343c34dff2b512907d516683871056928d3c13179a9fb5d5efba7b03c970f674b7b5997f22fc8ee7b9c4230cd0b1ed0b09d5227706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
